target 'FinalAlbum', :exclusive => true do
  pod "FinalAlbum", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FinalAlbum", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
